name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Log in to Heroku
      uses: akshnz/heroku-login-action@v2.0.0
      with:
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git@heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
