name: Deploy and Test

on:
  push:
    branches:
      - "temp_branch"  # Branche à surveillerr

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code
    - uses: actions/checkout@v3

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Exécuter les tests
    - name: Run Tests
      run: |
        pytest
    # Étape 5 : Si les tests passent, déployer sur Heroku
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    # Étape 6 : Login to Heroku
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: echo $HEROKU_API_KEY | heroku auth:token

    # Étape 7 : Ajouter Heroku remote et déployer
    - name: Add Heroku remote
      run: |
        git remote add heroku https://git.heroku.com/stormy-fjord-33387.git

    - name: Deploy to Heroku
      run: git push heroku temp_branch:main

