name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "Heroku CLI is installed"

      - name: Login to Heroku
        run: echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/credit-default-bis.git
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/credit-default-bis.git main
