name: Deploy and Test

on:
  push:
    branches:
      - "main" 
  deployment:
    branches:
      - "main"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code with full depth
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
          pip install matplotlib

      # Step 4: Verify required files
      - name: Verify required files
        run: |
          ls -R ./data
          unzip -l ./data/data_test.csv.zip  # Liste le contenu du fichier ZIP
          head -n 5 <(unzip -p ./data/data_test.csv.zip)  # Affiche les 5 premières lignes du CSV extrait

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          pytest test_flask_app.py

      # Step 6: (Optional) Install Heroku CLI
      - name: Install Heroku CLI
        if: always()
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 7: (Optional) Configure Heroku credentials
      - name: Configure Heroku credentials
        if: always()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc

      # Step 8: (Optional) Add Heroku remote
      - name: Add Heroku remote
        if: always()
        run: |
          if git remote | grep -q heroku; then
            git remote set-url heroku https://git.heroku.com/credit-default-01.git
          else
            git remote add heroku https://git.heroku.com/credit-default-01.git
          fi

      # Step 9: (Optional) Deploy to Heroku
      - name: Deploy to Heroku
        run: |
            git push heroku main:refs/heads/main
